[package]
name = "gws-cache"
version = "0.1.0"
authors = ["Albert Gomà i León"]
description = "Asynchronous cache for gws using Rust's port of SwissTable hash map."
edition = "2018"


[dependencies]
hashbrown = "0.7.1"
